import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import { registerSW } from 'virtual:pwa-register'

// Registers the service worker generated by vite-plugin-pwa so the app can
// be installed and works offline. `autoUpdate` means new versions are
// fetched and swapped in silently on the next load.
registerSW({ immediate: true })

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
